# Configuration du MicroBlog
site:
  name: Mon MicroBlog
  description: Mes pensées, liens et découvertes
  language: fr
author:
  name: Yoan Bernabeu
  bio: Développeur passionné | Tech enthusiast | Partage de découvertes
  avatar: /images/avatar.jpg
social:
  twitter: ''
  github: ''
  mastodon: ''
  linkedin: ''
  bluesky: ''
links:
  - label: Mon Blog
    url: https://example.com
  - label: Portfolio
    url: https://portfolio.example.com
feed:
  postsPerPage: 20
